/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer {
  'id' : bigint,
  'owner' : Principal,
  'timestamp' : bigint,
  'answerText' : string,
  'imageClueIds' : Array<bigint>,
}
export interface AudioClue {
  'id' : bigint,
  'owner' : Principal,
  'audioBlob' : ExternalBlob,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface ImageClue {
  'id' : bigint,
  'imageBlob' : ExternalBlob,
  'owner' : Principal,
  'timestamp' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoClue {
  'id' : bigint,
  'owner' : Principal,
  'videoBlob' : ExternalBlob,
  'timestamp' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateAnswer' : ActorMethod<[Array<bigint>, string], bigint>,
  'getAnswer' : ActorMethod<[bigint], [] | [Answer]>,
  'getAudioClue' : ActorMethod<[bigint], [] | [AudioClue]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getImageClue' : ActorMethod<[bigint], [] | [ImageClue]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoClue' : ActorMethod<[bigint], [] | [VideoClue]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'uploadAudioClue' : ActorMethod<[ExternalBlob], bigint>,
  'uploadImageClue' : ActorMethod<[ExternalBlob], bigint>,
  'uploadVideoClue' : ActorMethod<[ExternalBlob], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];