/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Answer = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'timestamp' : IDL.Int,
  'answerText' : IDL.Text,
  'imageClueIds' : IDL.Vec(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AudioClue = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'audioBlob' : ExternalBlob,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ImageClue = IDL.Record({
  'id' : IDL.Nat,
  'imageBlob' : ExternalBlob,
  'owner' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const VideoClue = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'videoBlob' : ExternalBlob,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateAnswer' : IDL.Func([IDL.Vec(IDL.Nat), IDL.Text], [IDL.Nat], []),
  'getAnswer' : IDL.Func([IDL.Nat], [IDL.Opt(Answer)], ['query']),
  'getAudioClue' : IDL.Func([IDL.Nat], [IDL.Opt(AudioClue)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getImageClue' : IDL.Func([IDL.Nat], [IDL.Opt(ImageClue)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoClue' : IDL.Func([IDL.Nat], [IDL.Opt(VideoClue)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadAudioClue' : IDL.Func([ExternalBlob], [IDL.Nat], []),
  'uploadImageClue' : IDL.Func([ExternalBlob], [IDL.Nat], []),
  'uploadVideoClue' : IDL.Func([ExternalBlob], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Answer = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'timestamp' : IDL.Int,
    'answerText' : IDL.Text,
    'imageClueIds' : IDL.Vec(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AudioClue = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'audioBlob' : ExternalBlob,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ImageClue = IDL.Record({
    'id' : IDL.Nat,
    'imageBlob' : ExternalBlob,
    'owner' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const VideoClue = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'videoBlob' : ExternalBlob,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateAnswer' : IDL.Func([IDL.Vec(IDL.Nat), IDL.Text], [IDL.Nat], []),
    'getAnswer' : IDL.Func([IDL.Nat], [IDL.Opt(Answer)], ['query']),
    'getAudioClue' : IDL.Func([IDL.Nat], [IDL.Opt(AudioClue)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getImageClue' : IDL.Func([IDL.Nat], [IDL.Opt(ImageClue)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoClue' : IDL.Func([IDL.Nat], [IDL.Opt(VideoClue)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadAudioClue' : IDL.Func([ExternalBlob], [IDL.Nat], []),
    'uploadImageClue' : IDL.Func([ExternalBlob], [IDL.Nat], []),
    'uploadVideoClue' : IDL.Func([ExternalBlob], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };